// Generated from the Babykelo YouTube channel (@babykelo0) + Drum Quarters features.
export const CHANNEL = {"subs": "7.03K subscribers", "avatar": "https://yt3.googleusercontent.com/3H0uP_AHL3hre_9NZOVL-U3SUIo71q10S__eBg507Qc5cReCx_Q8CqwQiu6AQ7NTusqE7Sah=s900-c-k-c0x00ffffff-no-rj", "count": 152, "views": 474748};
export const VIDEOS = [{"id":"q8ZH5ALAPK4","t":"TENSION ‼️","v":1000,"y":2026,"d":"2:45","s":0,"tags":["afro"],"src":"Babykelo"},
{"id":"1TQ1SMcwS54","t":"BORN IN THE 90’S COVER @shedtracks","v":1400,"y":2026,"d":"3:30","s":0,"tags":["afro"],"src":"Babykelo"},
{"id":"f5lTxJrs2eU","t":"SpongeBob ‼️","v":0,"y":null,"d":"1:41","s":0,"tags":["afro"],"src":"Babykelo"},
{"id":"7SBMR2FFYQ0","t":"He is exalted ‼️","v":436,"y":2026,"d":"1:25","s":0,"tags":["gospel"],"src":"Babykelo"},
{"id":"wCizFaSPzi8","t":"WHAT I WANT ‼️","v":548,"y":2026,"d":"1:32","s":0,"tags":["gospel"],"src":"Babykelo"},
{"id":"2tG9CuivQ1c","t":"PROCLAIM ‼️","v":314,"y":2026,"d":"1:33","s":0,"tags":["gospel"],"src":"Babykelo"},
{"id":"KjU1pYMKO64","t":"Groove","v":598,"y":2026,"d":"1:36","s":0,"tags":["afro"],"src":"Babykelo"},
{"id":"CNJFU4dEKq8","t":"TEKNO PRESS DRUM COVER","v":342,"y":2026,"d":"1:49","s":0,"tags":["afro"],"src":"Babykelo"},
{"id":"8oEhY0jnpY8","t":"Washed","v":984,"y":2026,"d":"1:31","s":0,"tags":["gospel"],"src":"Babykelo"},
{"id":"3g68-sW25aY","t":"Hale cover","v":708,"y":2026,"d":"1:40","s":0,"tags":["gospel"],"src":"Babykelo"},
{"id":"aMDNoWY0hqs","t":"WHAT A MIGHTY GOD","v":1700,"y":2026,"d":"2:15","s":0,"tags":["gospel"],"src":"Babykelo"},
{"id":"05g_TMtP2y4","t":"Proberbs 3 drum challenge","v":1400,"y":2026,"d":"1:29","s":0,"tags":["afro"],"src":"Babykelo"},
{"id":"eic8-jdyaI8","t":"COMMANDER COVER @shiiroszn","v":2500,"y":2025,"d":"2:09","s":0,"tags":["afro"],"src":"Babykelo"},
{"id":"IV_8MBDcKiY","t":"Series 3. With @flystickz_inc","v":433,"y":2025,"d":"2:28","s":0,"tags":["brands"],"src":"Babykelo"},
{"id":"iJm25JzbVL8","t":"Series 1 unveiling @Starblessing_ signature stick with @flystickz_inc · enjoy","v":1200,"y":2025,"d":"2:57","s":0,"tags":["brands"],"src":"Babykelo"},
{"id":"lhMlFlqEUfw","t":"Series 2. Unveiling @Dnathdrums signatures with @flystickz_inc","v":934,"y":2025,"d":"3:03","s":0,"tags":["brands"],"src":"Babykelo"},
{"id":"wqJrZ-hVpuY","t":"Anchor by @geraldbishung cover by meeee · .","v":757,"y":2025,"d":"1:26","s":0,"tags":["gospel"],"src":"Babykelo"},
{"id":"xoAFk688ySc","t":"EZE BY @officialMasterKraft x @babykelo0 (drum cover )","v":825,"y":2025,"d":"3:01","s":0,"tags":["afro"],"src":"Babykelo"},
{"id":"8lcNvgAEEwQ","t":"TREASURE BY @brunomars and @babykelo0","v":438,"y":2025,"d":"1:07","s":0,"tags":["afro"],"src":"Babykelo"},
{"id":"vVLeAKUJ3M0","t":"Nancy mulligan (folk version)by @EdSheeran","v":376,"y":2025,"d":"1:07","s":0,"tags":["afro"],"src":"Babykelo"},
{"id":"rbFsI83Z0Xw","t":"PROCESS","v":2100,"y":2025,"d":"2:34","s":0,"tags":["afro"],"src":"Babykelo"},
{"id":"Ud4tjU2dr9g","t":"Jireh reimagined","v":655,"y":2025,"d":"1:34","s":0,"tags":["gospel"],"src":"Babykelo"},
{"id":"6N_pZjCpgLs","t":"Me and @Blahktonez doing what we love","v":924,"y":2025,"d":"1:42","s":0,"tags":["afro"],"src":"Babykelo"},
{"id":"uYG9O81QPkc","t":"STABD BY YOU BY SPYRO X BABYKELO X HILLSPLAY","v":1600,"y":2025,"d":"2:28","s":0,"tags":["gospel"],"src":"Babykelo"},
{"id":"6MnOI_fDZO8","t":"@CententCymbalsgongs WITH @babykelo0 · .ARTIST UNVEILING","v":295,"y":2025,"d":"2:06","s":0,"tags":["brands"],"src":"Babykelo"},
{"id":"V-pu3AOpGYU","t":"KELO IS BACK","v":978,"y":2025,"d":"1:16","s":0,"tags":["afro"],"src":"Babykelo"},
{"id":"fzZ4Vhm6N08","t":"BABA BY VIKTOR KARO · BABYKELO SESSIONS","v":2000,"y":2025,"d":"2:39","s":0,"tags":["sessions","afro"],"src":"Babykelo"},
{"id":"3fGEDrIfkYs","t":"Babykelo playing Highlife · Babykelo sessions","v":3800,"y":2025,"d":"3:49","s":0,"tags":["sessions","afro"],"src":"Babykelo"},
{"id":"9D-lCO_PZHY","t":"OZUMBA MBADIWE REMIX · @reekadobanks · osadebey x BABYKELO SESSIONS · .","v":3800,"y":2025,"d":"2:33","s":0,"tags":["sessions","afro"],"src":"Babykelo"},
{"id":"dfhXt3UrFZc","t":"HMMMM @DavidoOfficial ft @ChrisBrownTV · BABYKELO SESSIONS · .","v":2600,"y":2025,"d":"3:02","s":0,"tags":["sessions","afro"],"src":"Babykelo"},
{"id":"722wVrBNh2k","t":"WOMAN COMMANDO BY @ayrastarrofficial · BABYKELO SESSIONS","v":2400,"y":2024,"d":"3:07","s":0,"tags":["sessions","afro"],"src":"Babykelo"},
{"id":"bu44fWF_3QI","t":"METAVERSE BY OLAMIDE X BABYKELO · .BABYKELO SESSIONS","v":1700,"y":2024,"d":"3:15","s":0,"tags":["sessions","afro"],"src":"Babykelo"},
{"id":"OebbOnidcZs","t":"SHORT SKIRT BY @Nasboi COVER · BABYKELO SESSIONS","v":1400,"y":2024,"d":"2:21","s":0,"tags":["sessions","afro"],"src":"Babykelo"},
{"id":"HgyO9P7u4_U","t":"LOCKED GROOVE WITH @vict0ny SOWETO · BABYKELO SESSIONS","v":2200,"y":2024,"d":"2:33","s":0,"tags":["sessions","afro"],"src":"Babykelo"},
{"id":"ep0y_QTIhQw","t":"OLAMIDE x YOUNGJOHN x PHEELZ - SYNCHRO SYSTEM · BABYKELO SESSIONS · .","v":1000,"y":2024,"d":"2:47","s":0,"tags":["sessions","afro"],"src":"Babykelo"},
{"id":"Uyl3SRDhS4o","t":"JUMP · BABYKELO SESSIONS · .","v":508,"y":2024,"d":"2:39","s":0,"tags":["sessions","afro"],"src":"Babykelo"},
{"id":"E19lE_QQGCg","t":"CONGRATULATIONS BY @EJNewton and @TimGodfreyWorld · BABYKELO SESSIONS · .","v":2300,"y":2024,"d":"3:27","s":0,"tags":["sessions","gospel"],"src":"Babykelo"},
{"id":"jfxZV5s2usQ","t":"Happy feet by @samuelgiveson · BABYKELO SESSIONS","v":3000,"y":2024,"d":"4:04","s":0,"tags":["sessions","gospel"],"src":"Babykelo"},
{"id":"k2McboLZlL0","t":"DJ TUNEZ X TEMS X BABYKELO · ONLY ME AND YOU REMIX","v":1200,"y":2024,"d":"6:25","s":0,"tags":["afro"],"src":"Babykelo"},
{"id":"Npi0hEF5p5E","t":"Yeaaaaaaaaaaaa","v":331,"y":2024,"d":"1:36","s":0,"tags":["afro"],"src":"Babykelo"},
{"id":"JVyOJggBOhM","t":"FILL THE ROOM MASHUP · BABYKELO SESSIONS","v":2400,"y":2024,"d":"1:36","s":0,"tags":["sessions","gospel"],"src":"Babykelo"},
{"id":"MQajzi0Bx_0","t":"VICTONY APOLLO · .BABYKELO SESSIONS","v":2100,"y":2024,"d":"2:32","s":0,"tags":["sessions","afro"],"src":"Babykelo"},
{"id":"B4DGsOrhECU","t":"APALA DISCO by dj Tunez, Wizkid,seyi vibez ,terry apala X BABYKELO SESSIONS · .","v":14000,"y":2024,"d":"3:32","s":0,"tags":["sessions","afro"],"src":"Babykelo"},
{"id":"pozgWI_btFY","t":"LIFT UP YOUR NAME HIGH · HILLSPLAY · BABYKELO SESSIONS","v":2400,"y":2024,"d":"2:22","s":0,"tags":["sessions","gospel"],"src":"Babykelo"},
{"id":"IE6fiEboWSk","t":"PALAVA BY @officialjohnnydrille · BABYKELO SESSIONS","v":3100,"y":2024,"d":"3:16","s":0,"tags":["sessions","afro"],"src":"Babykelo"},
{"id":"Xf0vb8dmNxc","t":"CAVEMEN BEAUTIFUL RAIN (Drum Cover) · BABYKELO SESSIONS","v":13000,"y":2024,"d":"3:17","s":0,"tags":["sessions","afro"],"src":"Babykelo"},
{"id":"NChNaQV4rXc","t":"PST IREN AGALLIO DRUM COVER · .BABYKELO SESSIONS","v":6600,"y":2024,"d":"1:52","s":0,"tags":["sessions","gospel"],"src":"Babykelo"},
{"id":"wCj2s0W7d-I","t":"WORK WORK WORK PART 2 · .BABYKELO SESSIONS","v":1000,"y":2024,"d":"3:37","s":0,"tags":["sessions","afro"],"src":"Babykelo"},
{"id":"wgbQULung0M","t":"RIHANNA WORK PART 1 · .BABYKELO SESSIONS","v":1100,"y":2024,"d":"3:37","s":0,"tags":["sessions","afro"],"src":"Babykelo"},
{"id":"PUhfc_xcBr8","t":"MICHEAL JACKSON · THEY DONT CARE ABOUT US (DRUM COVER)","v":1300,"y":2024,"d":"2:28","s":0,"tags":["afro"],"src":"Babykelo"},
{"id":"sfZJyDEwv88","t":"FAST LANE BY VAS · .Babykleo Sessions","v":677,"y":2024,"d":"5:34","s":0,"tags":["sessions","afro"],"src":"Babykelo"},
{"id":"1BNu-CkzsU0","t":"TERMINATOR BY @shedtracks","v":16000,"y":2024,"d":"4:44","s":0,"tags":["afro"],"src":"Babykelo"},
{"id":"rF6ZmezFdO8","t":"CREDIT ALERT KOCEE FT PATORANKING · .babykelo sessions","v":3700,"y":2024,"d":"3:14","s":0,"tags":["sessions","afro"],"src":"Babykelo"},
{"id":"kVLibsCAvu4","t":"PHEELZ GO LO DRUM COVER · babykelo sessions","v":2800,"y":2024,"d":"2:09","s":0,"tags":["sessions","afro"],"src":"Babykelo"},
{"id":"Lo5rTecxIuY","t":"Babykelo at @drumsessionlagos","v":1800,"y":2024,"d":"1:11","s":0,"tags":["sessions","live"],"src":"Babykelo"},
{"id":"klHlnbBB3qM","t":"BABYKELO IS CRAZY · .","v":1800,"y":2024,"d":"1:25","s":0,"tags":["afro"],"src":"Babykelo"},
{"id":"AhtS_akH2SI","t":"CELEBRATION CHURCH CHIOR X BABYKELO","v":7300,"y":2024,"d":"5:25","s":0,"tags":["gospel","live"],"src":"Babykelo"},
{"id":"ooQNC4aQ_7Y","t":"YOU AND ME Part 1 · @juicebox_music · .BABYKELO SESSIONS","v":2100,"y":2024,"d":"5:51","s":0,"tags":["sessions","afro"],"src":"Babykelo"},
{"id":"X_oHmRXWlBM","t":"Wait on You Dante Bowe and Chandler Moore| · BABYKELO SESSIONS · .","v":7800,"y":2024,"d":"3:20","s":0,"tags":["sessions","gospel"],"src":"Babykelo"},
{"id":"UN_-ous6G64","t":"Jesus is the way ,truth and life 🤲","v":770,"y":2024,"d":"0:58","s":0,"tags":["gospel"],"src":"Babykelo"},
{"id":"TBlu-wbe0GE","t":"YMMH COVER · .BABYKELO SESSIONS @cjdrumpro","v":6000,"y":2024,"d":"2:40","s":0,"tags":["sessions","afro"],"src":"Babykelo"},
{"id":"6ZNv2c2SOUc","t":"TEMS ME AND YOU COVER · BABYKELO SESSIONS","v":9800,"y":2024,"d":"1:16","s":0,"tags":["sessions","afro"],"src":"Babykelo"},
{"id":"kogDRU2g0Sg","t":"FEARLESS BY @officialflavour · .BABYKELO SESSIONS","v":5000,"y":2024,"d":"3:12","s":0,"tags":["sessions","afro"],"src":"Babykelo"},
{"id":"Q2ON-WfdqmQ","t":"BABYKELO SESSIONS · .buena by @Teoriah_","v":1300,"y":2024,"d":"2:51","s":0,"tags":["sessions","afro"],"src":"Babykelo"},
{"id":"3ucr1Ia3JHs","t":"BABYKELO SESSIONS · .Lord I love you remake","v":2900,"y":2024,"d":"1:24","s":0,"tags":["sessions","gospel"],"src":"Babykelo"},
{"id":"srtUFy6xauU","t":"PRAISE THE LORD REMIX · BABYKELO SESSIONS","v":1700,"y":2024,"d":"0:38","s":0,"tags":["sessions","gospel"],"src":"Babykelo"},
{"id":"prJf6tmrQns","t":"BABYKELO SESSIONS · .BHW track","v":2500,"y":2024,"d":"2:56","s":0,"tags":["sessions","afro"],"src":"Babykelo"},
{"id":"4BFemmjl2mk","t":"BABYKELO SESSIONS · .NYEM EGO @blaqbonezmusic","v":4000,"y":2024,"d":"2:37","s":0,"tags":["sessions","afro"],"src":"Babykelo"},
{"id":"ItbbVbHq2Ig","t":"BABYKELO SESSIONS · .Praise Break","v":4100,"y":2024,"d":"1:03","s":0,"tags":["sessions","gospel"],"src":"Babykelo"},
{"id":"hUMzpPPlNcg","t":"BABYKELO SESSIONS · Game Changer Part B · 😋","v":4500,"y":2024,"d":"2:43","s":0,"tags":["sessions","afro"],"src":"Babykelo"},
{"id":"2Axu6hl_7n0","t":"BABYKELO SESSIONS · Game Changer @officialflavour","v":10000,"y":2024,"d":"2:42","s":0,"tags":["sessions","afro"],"src":"Babykelo"},
{"id":"j-4I7lon1tI","t":"BABYKELO SESSIONS · citiboy by @BurnaBoy","v":9700,"y":2024,"d":"2:35","s":0,"tags":["sessions","afro"],"src":"Babykelo"},
{"id":"cxKxr7ORGP8","t":"SABI GIRL BY AYRA STARR COVER BY BABYKELO AND VICKYIANO","v":18000,"y":2023,"d":"1:26","s":0,"tags":["afro"],"src":"Babykelo"},
{"id":"Rdb02tVS8uM","t":"Babykelo with smj and blahktonez @ Hicc","v":15000,"y":2022,"d":"1:35","s":0,"tags":["live"],"src":"Babykelo"},
{"id":"u9WdW6z8YUQ","t":"Levels drum cover by babykelo","v":15000,"y":2022,"d":"2:49","s":0,"tags":["afro"],"src":"Babykelo"},
{"id":"I8ju44AQ_B8","t":"Babykelo killing it on this makossa vibe","v":14000,"y":2022,"d":"4:15","s":0,"tags":["afro"],"src":"Babykelo"},
{"id":"Wvpj-ymDbiA","t":"Babykelo with smj lift your name on high","v":9400,"y":2022,"d":"3:09","s":0,"tags":["gospel"],"src":"Babykelo"},
{"id":"IMnLjP2Scm0","t":"IN YOUR NAME BY ADA EHI LIVE @ DAYSTAR CHURCH · drum cam","v":15000,"y":2021,"d":"3:17","s":0,"tags":["gospel","live"],"src":"Babykelo"},
{"id":"oJhm7GnS9js","t":"Number 1 by Yemi tpx drum cover by babykelo","v":4300,"y":2021,"d":"1:17","s":0,"tags":["gospel"],"src":"Babykelo"},
{"id":"j--Pinnj8X0","t":"DOINGS BY ARYASTARR","v":3900,"y":2021,"d":"2:03","s":0,"tags":["afro"],"src":"Babykelo"},
{"id":"87R1HapnleY","t":"I Am Not Forgotten by Isreal Houghton (Drum Cover by Baby Kelo)","v":5300,"y":2021,"d":"4:06","s":0,"tags":["gospel"],"src":"Babykelo"},
{"id":"xrwNV3oRazA","t":"Gats live show part 3","v":566,"y":2021,"d":"3:37","s":0,"tags":["live"],"src":"Babykelo"},
{"id":"taU29Renw1k","t":"Gats drum live show part2","v":1000,"y":2021,"d":"3:36","s":0,"tags":["live"],"src":"Babykelo"},
{"id":"1n9dlDSBgK4","t":"Babykelo live at gatz drum show at owerri","v":2800,"y":2021,"d":"2:35","s":0,"tags":["live"],"src":"Babykelo"},
{"id":"RGmZxCcqg_k","t":"@babykelo x @tenientertainer","v":1600,"y":2020,"d":"1:19","s":0,"tags":["afro"],"src":"Babykelo"},
{"id":"vO2_n375JVI","t":"Rehearsals with @samuel giveson","v":29000,"y":2020,"d":"3:30","s":0,"tags":["gospel","live"],"src":"Babykelo"},
{"id":"VmnddFMLxyc","t":"More work","v":1400,"y":2020,"d":"2:44","s":0,"tags":["afro"],"src":"Babykelo"},
{"id":"4cSvkrq8bME","t":"Working out after a long time","v":805,"y":2020,"d":"1:22","s":0,"tags":["afro"],"src":"Babykelo"},
{"id":"T1OIIfnECss","t":"Babykelo","v":1500,"y":2020,"d":"1:24","s":0,"tags":["afro"],"src":"Babykelo"},
{"id":"4ax50AOJcrY","t":"Babykelo","v":1600,"y":2020,"d":"1:15","s":0,"tags":["afro"],"src":"Babykelo"},
{"id":"y9QPAfWGVaA","t":"Me enjoying a beat I made · babykelo also produces","v":932,"y":2020,"d":"1:10","s":0,"tags":["afro"],"src":"Babykelo"},
{"id":"w2MzKenpo7M","t":"Playing in your name in Sierraleone","v":5100,"y":2020,"d":"2:54","s":0,"tags":["gospel","live"],"src":"Babykelo"},
{"id":"DyvZPRFFIdQ","t":"More more more","v":749,"y":2020,"d":"1:01","s":0,"tags":["afro"],"src":"Babykelo"},
{"id":"xdnyNVnpUAk","t":"Babykelo performing on high @the outsider","v":18000,"y":2020,"d":"5:13","s":0,"tags":["gospel","live"],"src":"Babykelo"},
{"id":"_wyCsjC1mgE","t":"Me pushing hard","v":1200,"y":2020,"d":"1:24","s":0,"tags":["afro"],"src":"Babykelo"},
{"id":"TUQ5A8RGjEs","t":"Something light 5 ‼️ with the amazing chioma","v":160,"y":null,"d":"","s":1,"tags":["shorts"],"src":"Babykelo"},
{"id":"M9hfDrN7feU","t":"Something light 5 ‼️","v":251,"y":null,"d":"","s":1,"tags":["shorts"],"src":"Babykelo"},
{"id":"6hFkOOh4bTs","t":"Something light 4‼️ ft @LagosBfingerz","v":384,"y":null,"d":"","s":1,"tags":["shorts"],"src":"Babykelo"},
{"id":"m02S2R_2sQU","t":"Something light 3‼️","v":657,"y":null,"d":"","s":1,"tags":["shorts"],"src":"Babykelo"},
{"id":"-Beyg68bJvc","t":"Something light ‼️","v":584,"y":null,"d":"","s":1,"tags":["shorts"],"src":"Babykelo"},
{"id":"1SYbRz7NM0A","t":"Fun time","v":463,"y":null,"d":"","s":1,"tags":["shorts"],"src":"Babykelo"},
{"id":"5MUVcXUzwEE","t":"Solo from heaven","v":934,"y":null,"d":"","s":1,"tags":["shorts"],"src":"Babykelo"},
{"id":"DOBTkIlnhbk","t":"Kompa madness 2 ‼️","v":918,"y":null,"d":"","s":1,"tags":["shorts"],"src":"Babykelo"},
{"id":"zp_gjrz4w2Y","t":"Kompa Madness ‼️","v":622,"y":null,"d":"","s":1,"tags":["shorts"],"src":"Babykelo"},
{"id":"4jfVul8scOg","t":"WHAT I NEED ‼️","v":2100,"y":null,"d":"","s":1,"tags":["shorts","gospel"],"src":"Babykelo"},
{"id":"tnu5jlx3VSQ","t":"No one‼️","v":2400,"y":null,"d":"","s":1,"tags":["shorts"],"src":"Babykelo"},
{"id":"LZGikIRjXkY","t":"May 1, 2026","v":1600,"y":null,"d":"","s":1,"tags":["shorts"],"src":"Babykelo"},
{"id":"zrC1EB-o5AE","t":"Drums talking","v":2000,"y":null,"d":"","s":1,"tags":["shorts"],"src":"Babykelo"},
{"id":"CFm9aAa2L1U","t":"Happy new month was","v":2100,"y":null,"d":"","s":1,"tags":["shorts"],"src":"Babykelo"},
{"id":"YUCRnBNmwW4","t":"When commander says go in","v":2400,"y":null,"d":"","s":1,"tags":["shorts"],"src":"Babykelo"},
{"id":"sFMKxG-Va-Y","t":"Locked in 😭","v":2500,"y":null,"d":"","s":1,"tags":["shorts"],"src":"Babykelo"},
{"id":"5YPV-8uOmR4","t":"When @brunomars says solo","v":1600,"y":null,"d":"","s":1,"tags":["shorts"],"src":"Babykelo"},
{"id":"71xN1AZm8ZU","t":"Do for love cover","v":3100,"y":null,"d":"","s":1,"tags":["shorts"],"src":"Babykelo"},
{"id":"_qyZAJ0tkMY","t":"Centent artist babykelo","v":1900,"y":null,"d":"","s":1,"tags":["shorts","brands"],"src":"Babykelo"},
{"id":"tK7BFd14K0Y","t":"Baby is back","v":2000,"y":null,"d":"","s":1,"tags":["shorts"],"src":"Babykelo"},
{"id":"_QAG0bGQn2A","t":"When you asked to do a solo","v":2200,"y":null,"d":"","s":1,"tags":["shorts"],"src":"Babykelo"},
{"id":"Iy2oMFoY-tE","t":"Hmmmmmmm babykelo is angry","v":1700,"y":null,"d":"","s":1,"tags":["shorts"],"src":"Babykelo"},
{"id":"0SIf2pRv9PA","t":"Which take do you prefer from this intro · official song by @DunsinOyekan and arranged by tunez","v":1200,"y":null,"d":"","s":1,"tags":["shorts","gospel"],"src":"Babykelo"},
{"id":"FMjbk6NC4JE","t":"Drummer goes wild on woman commando song by @ayrastarrofficial","v":1000,"y":null,"d":"","s":1,"tags":["shorts"],"src":"Babykelo"},
{"id":"UPJYdEWlEzQ","t":"Insane shed track 🔥🔥🔥🔥🔥🔥🔥🔥🔥","v":1300,"y":null,"d":"","s":1,"tags":["shorts"],"src":"Babykelo"},
{"id":"kGNdilRVTew","t":"Mad solo","v":3500,"y":null,"d":"","s":1,"tags":["shorts"],"src":"Babykelo"},
{"id":"aiouZIIFk3o","t":"Short skirt vibes by @Nasboi","v":988,"y":null,"d":"","s":1,"tags":["shorts"],"src":"Babykelo"},
{"id":"Gg-SBPlo5LU","t":"Jump jump jump","v":681,"y":null,"d":"","s":1,"tags":["shorts"],"src":"Babykelo"},
{"id":"IFw5Vk8Zp08","t":"Congratulations to babykelo as best drummer","v":1400,"y":null,"d":"","s":1,"tags":["shorts","gospel"],"src":"Babykelo"},
{"id":"623BZQxdaWs","t":"One of the best drummer in Nigeria goes crazy on @samuelgiveson track","v":1800,"y":null,"d":"","s":1,"tags":["shorts","gospel"],"src":"Babykelo"},
{"id":"5hqG4nkiYVc","t":"Vibe","v":585,"y":null,"d":"","s":1,"tags":["shorts"],"src":"Babykelo"},
{"id":"MaQrHKyeQYI","t":"July 1, 2024","v":819,"y":null,"d":"","s":1,"tags":["shorts"],"src":"Babykelo"},
{"id":"QT90e4R0xus","t":"Palava · speechless","v":746,"y":null,"d":"","s":1,"tags":["shorts"],"src":"Babykelo"},
{"id":"dZS-nUKxnOA","t":"Beautiful rain by babykelo","v":704,"y":null,"d":"","s":1,"tags":["shorts"],"src":"Babykelo"},
{"id":"Lu48ICeiFgU","t":"AGALLIO BY PST IREN","v":1700,"y":null,"d":"","s":1,"tags":["shorts","gospel"],"src":"Babykelo"},
{"id":"hq3Jh42Y0cU","t":"WORK WORK WORK GOES WILD · .shhhhh","v":810,"y":null,"d":"","s":1,"tags":["shorts"],"src":"Babykelo"},
{"id":"XpvL7IbISSw","t":"MICHEAL JACKSON SONG BEEN DEVOURED BY BABYKELO · .CRAZYYY","v":1100,"y":null,"d":"","s":1,"tags":["shorts"],"src":"Babykelo"},
{"id":"yX6hlDx_3cI","t":"Hot bars by babykelo","v":449,"y":null,"d":"","s":1,"tags":["shorts"],"src":"Babykelo"},
{"id":"aW-cnolZwcA","t":"Terminator solo · crazy bars @shedtracks","v":1300,"y":null,"d":"","s":1,"tags":["shorts"],"src":"Babykelo"},
{"id":"-3cODeNM7xc","t":"Drummer Goes Wild On Go Low By @pheelz","v":848,"y":null,"d":"","s":1,"tags":["shorts"],"src":"Babykelo"},
{"id":"iV7zSX81w6s","t":"Go low by ​@pheelz","v":584,"y":null,"d":"","s":1,"tags":["shorts"],"src":"Babykelo"},
{"id":"enTEwGLyUhI","t":"Drummer goes wild","v":14000,"y":null,"d":"","s":1,"tags":["shorts"],"src":"Babykelo"},
{"id":"555WCfBU_vk","t":"Jesus reigns 🤲","v":1000,"y":null,"d":"","s":1,"tags":["shorts","gospel"],"src":"Babykelo"},
{"id":"-Kj_C-HiHUY","t":"Wait on the lord by dantebowe","v":1100,"y":null,"d":"","s":1,"tags":["shorts","gospel"],"src":"Babykelo"},
{"id":"rBUFS7w7FnA","t":"JESUS IS THE WAY,TRUTH AND LIFE","v":1500,"y":null,"d":"","s":1,"tags":["shorts","gospel"],"src":"Babykelo"},
{"id":"vpWaeBxS-FM","t":"Trying to stretch with glut track by @NickSmithGlobal","v":1200,"y":null,"d":"","s":1,"tags":["shorts"],"src":"Babykelo"},
{"id":"Ym0Bby1ngWc","t":"Buena by @Teoriah_ drum cover","v":880,"y":null,"d":"","s":1,"tags":["shorts"],"src":"Babykelo"},
{"id":"4Xc825r9sJo","t":"Babykelo with ada in 🇨🇲","v":7400,"y":null,"d":"","s":1,"tags":["shorts","gospel","live"],"src":"Babykelo"},
{"id":"asQ6uuQxwkU","t":"Rehearsal","v":4500,"y":null,"d":"","s":1,"tags":["shorts","live"],"src":"Babykelo"},
{"id":"oEpYbuNqTtc","t":"Am free drum solo","v":7900,"y":null,"d":"","s":1,"tags":["shorts"],"src":"Babykelo"},
{"id":"MsHHub_VAPg","t":"Babykelo having fun","v":2700,"y":null,"d":"","s":1,"tags":["shorts"],"src":"Babykelo"},
{"id":"jrped_loRGc","t":"Terminator – Baby Kelo | Drum Performance","v":5500,"y":2024,"d":"","s":0,"tags":["features","afro"],"src":"Drum Quarters"},
{"id":"juaC0P1IRek","t":"Game Changer – Flavour | Babykelo Drum Cover","v":0,"y":2024,"d":"","s":0,"tags":["features","afro"],"src":"Drum Quarters"},
{"id":"M6BPqaJ9ZfY","t":"Drum Chops 101 – Lily Drum Play-through","v":1000,"y":2024,"d":"","s":0,"tags":["features","afro"],"src":"Drum Quarters"},
{"id":"d98kSc6bi14","t":"Baby Kelo Performs Beyoncé's Party","v":898,"y":2024,"d":"","s":0,"tags":["features","afro"],"src":"Drum Quarters"},
{"id":"eHcExVZMjs0","t":"BabyKelo shares his story & tips to becoming a successful drummer","v":0,"y":null,"d":"","s":0,"tags":["features","afro"],"src":"Toch Sticks Music"},
{"id":"2Y2iI1thk7E","t":"DrumChat with Babykelo – Tips for Beginner Drummers","v":0,"y":2024,"d":"","s":0,"tags":["features","afro"],"src":"Drum Quarters"}];
